language: ruby
before_install:
  - 'echo "gem: --no-ri --no-rdoc" > ~/.gemrc'
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version
#  - gem install json --version 1.8.1
bundler_args: --without development
cache: bundler

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head    # The latest Ruby, whatever version it happens to be.
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - 1.8.7
  - ree          # Ruby Enterprise Edition

matrix:
  allow_failures:
    - rvm: rbx            # rbx has been problematic.
  include:
    - rvm: rbx
      gemfile: gemfiles/Gemfile.rbx
    - rvm: 2.1.0
      env: COVERAGE=true
  exclude:
    - rvm: rbx
      gemfile: Gemfile

# blacklist
branches:
  except:
    - rt-site
    - gh-pages
