language: ruby
bundler_args: --without development
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head    # The latest Ruby, whatever version it happens to be.
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx
  - 1.8.7
  - ree          # Ruby Enterprise Edition
# blacklist
branches:
  except:
    - rt-site
    - gh-pages
