language: ruby
before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version
  - gem install json --version 1.8.1
bundler_args: --without development
cache: bundler

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
#  - ruby-head    # The latest Ruby, whatever version it happens to be.
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
#  - rbx-2.1.1   # rbx has been problematic in Travis.
  - 1.8.7
  - ree          # Ruby Enterprise Edition
# blacklist
branches:
  except:
    - rt-site
    - gh-pages
